### ISSUE TITLE
BoilerPlate

### ISSUE THREAD

**Issue by MrCartree** [imbingz/Ultimate-Streaming-Guide#1]
We need to add html boilerplate and link all other pages (css, js)

**Comment by MrCartree** [comment]
Excellent work!

**Comment by LayneHansen** [comment]
If you and zach want to get to work on the project that's fine. Having to
work full time during this course really sucks. But I don't want to hold up
the project because i'm not available during the day. I can always help
with tweaks, improvements, etc. And I am willing to design our
presentation.

Layne
